remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Fakeshop FAQ - Verbraucherhilfe
description: Auf dieser Webseite erfahren sie alles rund um Fakeshops und deren gefahren!
